"""Switched relationship column for user and register table

Revision ID: 08f599ff8e24
Revises: 13d3f16544df
Create Date: 2024-06-19 06:50:03.544157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f599ff8e24'
down_revision = '13d3f16544df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_constraint('fk_register_users_id_user', type_='foreignkey')
        batch_op.drop_column('users_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])
        batch_op.create_foreign_key(batch_op.f('fk_user_users_id_register'), 'register', ['users_id'], ['idno'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_users_id_register'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.drop_column('users_id')

    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_register_users_id_user', 'user', ['users_id'], ['id'])

    # ### end Alembic commands ###
