"""rolled back

Revision ID: 0947de67580a
Revises: 08f599ff8e24
Create Date: 2024-06-19 07:01:20.530082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0947de67580a'
down_revision = '08f599ff8e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_register_users_id_user'), 'user', ['users_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_users_id_register', type_='foreignkey')
        batch_op.drop_column('users_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_users_id_register', 'register', ['users_id'], ['idno'])

    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_register_users_id_user'), type_='foreignkey')
        batch_op.drop_column('users_id')

    # ### end Alembic commands ###
