"""added column to store officer reports

Revision ID: 0be3d73dfda1
Revises: 405a7ad0cf61
Create Date: 2024-07-07 11:13:51.890145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be3d73dfda1'
down_revision = '405a7ad0cf61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reports', sa.Text(), nullable=True))
        batch_op.drop_column('officer_report')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer_report', sa.TEXT(), nullable=True))
        batch_op.drop_column('reports')

    # ### end Alembic commands ###
