"""added table for case report

Revision ID: 0e4a188fc510
Revises: 3d41316a1f0b
Create Date: 2024-07-04 00:10:41.936066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4a188fc510'
down_revision = '3d41316a1f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('crime_type', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=40), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.officer_id'], name=op.f('fk_case_report_officer_id_officers')),
    sa.PrimaryKeyConstraint('report_id', name=op.f('pk_case_report'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_report')
    # ### end Alembic commands ###
