"""added a column for date received on Messages table

Revision ID: 1c66e6b4a2bb
Revises: b0af7adab887
Create Date: 2024-06-28 12:49:24.925845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c66e6b4a2bb'
down_revision = 'b0af7adab887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_received', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('date_received')

    # ### end Alembic commands ###
