"""renamed register table

Revision ID: 22afc5781010
Revises: de3da497701a
Create Date: 2024-07-03 16:40:05.599637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22afc5781010'
down_revision = 'de3da497701a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officers',
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('officer_email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('badge', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.String(length=10), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('officer_id', name=op.f('pk_officers')),
    sa.UniqueConstraint('username', name=op.f('uq_officers_username'))
    )
    op.drop_table('officer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer',
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('badge', sa.VARCHAR(length=20), nullable=False),
    sa.Column('rank', sa.VARCHAR(length=10), nullable=False),
    sa.Column('station', sa.VARCHAR(length=20), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('officer_email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('officer_id', sa.INTEGER(), nullable=False),
    sa.UniqueConstraint('username', name='uq_officer_username')
    )
    op.drop_table('officers')
    # ### end Alembic commands ###
