"""added phone number column on crime table

Revision ID: 29d3d52f65de
Revises: cde46be0838e
Create Date: 2024-07-01 15:45:49.073850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d3d52f65de'
down_revision = 'cde46be0838e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phonenumber', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.drop_column('phonenumber')

    # ### end Alembic commands ###
