"""added columns for image upload

Revision ID: 2eff59369d20
Revises: d2a2b76b6cbd
Create Date: 2024-06-26 11:14:17.862085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eff59369d20'
down_revision = 'd2a2b76b6cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mimetype', sa.Text(), nullable=True))
        batch_op.alter_column('file_upload',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_crime_file_upload'), ['file_upload'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_crime_file_upload'), type_='unique')
        batch_op.alter_column('file_upload',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.drop_column('mimetype')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
