"""Removed theft table

Revision ID: 3d41316a1f0b
Revises: 22afc5781010
Create Date: 2024-07-03 22:57:26.361877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d41316a1f0b'
down_revision = '22afc5781010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theft')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theft',
    sa.Column('theft_id', sa.INTEGER(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('place_of_theft', sa.VARCHAR(length=50), nullable=False),
    sa.Column('street_address', sa.VARCHAR(length=30), nullable=False),
    sa.Column('city', sa.VARCHAR(length=10), nullable=False),
    sa.Column('date_of_theft', sa.VARCHAR(length=10), nullable=False),
    sa.Column('reported_by', sa.VARCHAR(length=10), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=False),
    sa.Column('time_of_theft', sa.VARCHAR(length=10), nullable=False),
    sa.Column('stolen_property', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('theft_status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('theft_file_upload', sa.TEXT(), nullable=True),
    sa.Column('theft_file_name', sa.TEXT(), nullable=True),
    sa.Column('theft_mimetype', sa.TEXT(), nullable=True),
    sa.Column('date_theft_received', sa.DATETIME(), nullable=False),
    sa.Column('victim_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['victim_id'], ['user.id'], name='fk_theft_victim_id_user'),
    sa.PrimaryKeyConstraint('theft_id', name='pk_theft')
    )
    # ### end Alembic commands ###
