"""added column to store officer reports

Revision ID: 405a7ad0cf61
Revises: f1ad4d5fc033
Create Date: 2024-07-06 15:21:57.284108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405a7ad0cf61'
down_revision = 'f1ad4d5fc033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer_report', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.drop_column('officer_report')

    # ### end Alembic commands ###
