"""removed unique of image uploaded

Revision ID: 49aeb4480e90
Revises: 914267bc60c5
Create Date: 2024-06-27 03:50:44.442448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49aeb4480e90'
down_revision = '914267bc60c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.drop_constraint('uq_crime_file_upload', type_='unique')

    with op.batch_alter_table('theft', schema=None) as batch_op:
        batch_op.drop_constraint('uq_theft_file_upload', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theft', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_theft_file_upload', ['file_upload'])

    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_crime_file_upload', ['file_upload'])

    # ### end Alembic commands ###
