"""modified columns for coodinates

Revision ID: 49f75709cf2c
Revises: 848ed032cf9b
Create Date: 2024-06-27 18:34:06.129644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f75709cf2c'
down_revision = '848ed032cf9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.drop_column('crime_latitude')
        batch_op.drop_column('crime_longitude')

    with op.batch_alter_table('theft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.drop_column('theft_longitude')
        batch_op.drop_column('theft_latitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theft_latitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('theft_longitude', sa.FLOAT(), nullable=True))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crime_longitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('crime_latitude', sa.FLOAT(), nullable=True))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
