"""added one table for officer registration

Revision ID: 4e46f1dd065d
Revises: 855e08f74766
Create Date: 2024-07-03 16:25:34.347642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e46f1dd065d'
down_revision = '855e08f74766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('officer_register')
    with op.batch_alter_table('officer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_no', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('officer_email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_officer_username'), ['username'])
        batch_op.drop_column('officer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_officer_username'), type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('officer_email')
        batch_op.drop_column('username')
        batch_op.drop_column('reg_no')

    op.create_table('officer_register',
    sa.Column('reg_no', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('officer_email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('reg_no', name='pk_officer_register'),
    sa.UniqueConstraint('username', name='uq_officer_register_username')
    )
    # ### end Alembic commands ###
