"""added column for assigned officer

Revision ID: 4f6c82449db6
Revises: 68d51998c78b
Create Date: 2024-07-04 16:09:45.689283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6c82449db6'
down_revision = '68d51998c78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_officer', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.drop_column('assigned_officer')

    # ### end Alembic commands ###
