"""added a column in Theft table reported_by

Revision ID: 5a7f897c8856
Revises: 0947de67580a
Create Date: 2024-06-23 12:19:45.056493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7f897c8856'
down_revision = '0947de67580a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.alter_column('issued_by',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('theft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_by', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theft', schema=None) as batch_op:
        batch_op.drop_column('reported_by')

    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.alter_column('issued_by',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
