"""added column for case reports

Revision ID: 68d51998c78b
Revises: 822e94b755eb
Create Date: 2024-07-04 15:33:04.217018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d51998c78b'
down_revision = '822e94b755eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('assigned_officer_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_case_report_officer_id_officers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_case_report_assigned_officer_id_officers'), 'officers', ['assigned_officer_id'], ['officer_id'])
        batch_op.drop_column('officer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_case_report_assigned_officer_id_officers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_case_report_officer_id_officers', 'officers', ['officer_id'], ['officer_id'])
        batch_op.drop_column('assigned_officer_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
