"""added column for time created

Revision ID: 822e94b755eb
Revises: 0e4a188fc510
Create Date: 2024-07-04 07:23:00.012532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822e94b755eb'
down_revision = '0e4a188fc510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
