"""added column for coodinates

Revision ID: 848ed032cf9b
Revises: 2c00060ad8bb
Create Date: 2024-06-27 17:32:07.422901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848ed032cf9b'
down_revision = '2c00060ad8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crime_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('crime_longitude', sa.Float(), nullable=True))

    with op.batch_alter_table('theft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theft_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('theft_longitude', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('theft', schema=None) as batch_op:
        batch_op.drop_column('theft_longitude')
        batch_op.drop_column('theft_latitude')

    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.drop_column('crime_longitude')
        batch_op.drop_column('crime_latitude')

    # ### end Alembic commands ###
