"""added table for officer registration

Revision ID: 855e08f74766
Revises: 91db98bed6af
Create Date: 2024-07-03 15:57:17.148703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855e08f74766'
down_revision = '91db98bed6af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer_register',
    sa.Column('reg_no', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('officer_email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('reg_no', name=op.f('pk_officer_register')),
    sa.UniqueConstraint('username', name=op.f('uq_officer_register_username'))
    )
    with op.batch_alter_table('officer', schema=None) as batch_op:
        batch_op.drop_column('officer_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer_email', sa.VARCHAR(length=120), nullable=False))

    op.drop_table('officer_register')
    # ### end Alembic commands ###
