"""added columns for uploading media and chnaged timezones used

Revision ID: 88ee6c984c16
Revises: afc8991ae875
Create Date: 2024-07-14 10:55:38.628614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ee6c984c16'
down_revision = 'afc8991ae875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('filename', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mimetype', sa.Text(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('mimetype')
        batch_op.drop_column('filename')
        batch_op.drop_column('media')

    # ### end Alembic commands ###
