"""added columns for image upload on theft table

Revision ID: 914267bc60c5
Revises: 2eff59369d20
Create Date: 2024-06-26 12:18:42.356440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914267bc60c5'
down_revision = '2eff59369d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_upload', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mimetype', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_theft_file_upload'), ['file_upload'])
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.BLOB(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_theft_file_upload'), type_='unique')
        batch_op.drop_column('mimetype')
        batch_op.drop_column('name')
        batch_op.drop_column('file_upload')

    # ### end Alembic commands ###
