"""added table for officer

Revision ID: 91db98bed6af
Revises: 29d3d52f65de
Create Date: 2024-07-03 13:29:43.159036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91db98bed6af'
down_revision = '29d3d52f65de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer',
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('officer_email', sa.String(length=120), nullable=False),
    sa.Column('badge', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.String(length=10), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('officer_id', name=op.f('pk_officer'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('officer')
    # ### end Alembic commands ###
