"""added a column for reply in Message table

Revision ID: a8ab84bd668d
Revises: 1c66e6b4a2bb
Create Date: 2024-06-28 14:20:17.175915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ab84bd668d'
down_revision = '1c66e6b4a2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('reply')

    # ### end Alembic commands ###
