"""Addes status column on Crime table

Revision ID: aed5a3625f90
Revises: cbc8946851b8
Create Date: 2024-06-25 14:54:43.237249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed5a3625f90'
down_revision = 'cbc8946851b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
