"""added a column for phone number in officers table

Revision ID: c122cb84ae67
Revises: b1c862af922f
Create Date: 2024-07-25 12:03:53.061429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c122cb84ae67'
down_revision = 'b1c862af922f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phonenumber', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.drop_column('phonenumber')

    # ### end Alembic commands ###
