"""added phone number column on crime table

Revision ID: cde46be0838e
Revises: a0874c33fe08
Create Date: 2024-07-01 15:35:51.142747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde46be0838e'
down_revision = 'a0874c33fe08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phonenumber', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.drop_column('phonenumber')

    # ### end Alembic commands ###
