"""removed columns

Revision ID: d2a2b76b6cbd
Revises: aed5a3625f90
Create Date: 2024-06-26 10:22:44.377228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a2b76b6cbd'
down_revision = 'aed5a3625f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_crime')
    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.alter_column('suspect_details',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('theft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theft', schema=None) as batch_op:
        batch_op.drop_column('data')

    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.alter_column('suspect_details',
               existing_type=sa.TEXT(),
               nullable=False)

    op.create_table('_alembic_tmp_crime',
    sa.Column('crime_id', sa.INTEGER(), nullable=False),
    sa.Column('date_of_incident', sa.VARCHAR(length=10), nullable=False),
    sa.Column('issued_by', sa.VARCHAR(length=20), nullable=True),
    sa.Column('time_of_incident', sa.VARCHAR(length=10), nullable=False),
    sa.Column('incident_location', sa.TEXT(), nullable=False),
    sa.Column('incident_nature', sa.TEXT(), nullable=False),
    sa.Column('incident_details', sa.TEXT(), nullable=False),
    sa.Column('suspect_details', sa.TEXT(), nullable=True),
    sa.Column('arrest_history', sa.TEXT(), nullable=False),
    sa.Column('suspect_name', sa.VARCHAR(length=10), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.Column('file_upload', sa.BLOB(), nullable=False),
    sa.Column('date_received', sa.DATETIME(), nullable=False),
    sa.Column('reporter_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('crime_id')
    )
    # ### end Alembic commands ###
