"""changed primary key column of officer table

Revision ID: de3da497701a
Revises: 035605db75a4
Create Date: 2024-07-03 16:35:28.637974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3da497701a'
down_revision = '035605db75a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer_id', sa.Integer(), nullable=False))
        batch_op.drop_column('reg_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_no', sa.INTEGER(), nullable=False))
        batch_op.drop_column('officer_id')

    # ### end Alembic commands ###
